# Generated by Django 3.1 on 2020-10-18 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=10)),
                ('dt_nascimento', models.DateTimeField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.escola')),
            ],
        ),
    ]
